language: go
sudo: false

before_script:
  - go get -u github.com/gorilla/websocket
  - go get -u github.com/blendlabs/go-assert
  - go get -u github.com/blendlabs/go-request
  - go get -u github.com/blendlabs/go-exception

script: 
  - go vet
  - go test